### ISSUE TITLE
[Rules] Flesh out `pop_slot_item_with_rules`

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/cw-croncat#105]
I noted that in this PR there's an area with a commented out function, `pop_slot_item_with_rules`

As we hustle to get our MVP ready for Cosmoverse, I totally get it! I thought I'd make a ticket to ensure we don't lose track of finishing that function.

See this comment, which is around the area of the function:
https://github.com/CronCats/cw-croncat/pull/104/files#r975953271

**Comment by TrevorJTClarke** [comment]
good catch @mikedotexe! going to consider this priority for beta release, unless there's no other cleanup for tasks with rules.
