### ISSUE TITLE
Move agent_nomination_begin_time out of Config

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/cw-croncat#11]
The items in Config (see `state.rs`) are supposed to be fields that can be changed and updated by a DAO vote.

I accidentally put `agent_nomination_begin_time` in the Config, but this field does not belong in config. This field is set programmatically when a new task is added, such that an agent in the pending queue can see if they can become an active agent.

### The reason why we have this

Let's say there's 1 agent in the active queue and 3 agents in the pending queue. A few tasks are added such that **one** agent from the pending queue is allowed to accept nomination and join the active agent queue. We want to respect the first-come, first-serve nature of the pending queue and give the first person in line a chance to accept the nomination. However, it's possible the first person in line is unresponsive. In order to keep things moving, we keep track of the "begin time" for this nomination. We use another field in Config (that should remain there) called `agent_nomination_duration` to determine how long to wait for the first person in the queue to respond. Or, perhaps the second person is also unresponsive, so after this duration happens again, the third person in line is able to nominate themselves.

Since `agent_nomination_begin_time` is not really a configuration setting that can or should be updated, it's probably best to put this as a field under the `CwCroncat` struct (also in `state.rs`) and make sure that all read and writes work as expected.

As usual, all tests should pass when this ticket is complete. (You can run `./test.sh` in the project root) In particular, I think this test will be a good one to run during development of this ticket: `accept_nomination_agent`

One way I like to run this test is by creating my own little bash script (remember to make it executable) that has this:

`my-test.sh`

```bash
#!/bin/bash
env RUSTFLAGS='-C link-arg=-s' cargo unit-test accept_nomination_agent -- --nocapture
```

This will only run that test and since we have `-- --nocapture` you can write to the console with `println`

Typically that looks like this:

```rs
// good for simple types
println!("debug {}", debug_var);
// or show an object
println!("debug {:?}", debug_var);
// or pretty-print, if it's available
println!("debug {:#?}", debug_var);
```

**Comment by Buckram123** [comment]
Closed by #13
