### ISSUE TITLE
Fix failure of `withdraw_reward` if agent received `agent_fee`

### ISSUE THREAD

**Issue by NinoLipartiia** [CronCats/cw-croncat#112]
If agent calls `proxy_call` and doesn't execute a task, croncat accrues them small `agent_fee`, which agent can receive with `withdraw_reward`.  But since `agent_fee` isn't included in task balance, the contract doesn't have enough funds to pay agent, thus `withdraw_reward` fails.

I think we should revise payment logic to avoid errors like this.

**Comment by mikedotexe** [comment]
Thank you, and here's a good comment referencing expected values:
https://github.com/CronCats/cw-croncat/pull/108#issuecomment-1255879910

**Comment by NinoLipartiia** [comment]
https://github.com/CronCats/cw-croncat/pull/108
