### ISSUE TITLE
[Important] Address agent fee being high

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/cw-croncat#117]
As we discussed, the agent fee is too high so we'll want to make some changes to this.

I think it'll be easiest to test this all out on a local chain using the new scripts Raf and Nino have made.

Misha pointed out this line may want to be adjusted:
https://github.com/CronCats/cw-croncat/blob/e0a4e5fed2cc7bf827752114acd8bade6a809c3d/contracts/cw-croncat/src/contract.rs#L60

We can also consider adjusting the defaults set during instantiation, like:
https://github.com/CronCats/cw-croncat/blob/e0a4e5fed2cc7bf827752114acd8bade6a809c3d/contracts/cw-croncat/src/contract.rs#L19

This might be another thing to look at:
https://github.com/CronCats/cw-croncat/blob/e0a4e5fed2cc7bf827752114acd8bade6a809c3d/contracts/cw-croncat/src/contract.rs#L61

And, more unlikely, we can take a look at:
https://github.com/CronCats/cw-croncat/blob/e0a4e5fed2cc7bf827752114acd8bade6a809c3d/contracts/cw-croncat/src/contract.rs#L59

**Comment by TrevorJTClarke** [comment]
I believe this may have gotten fixed in #108
