### ISSUE TITLE
`last_missed_slot` is always zero

### ISSUE THREAD

**Issue by NinoLipartiia** [CronCats/cw-croncat#124]
Field `last_missed_slot` in `Agent` should probably be updated by agent if they see the other agent miss a slot. Also we should use it to check the amount of tasks the agent skipped and eject bad agents.

**Comment by TrevorJTClarke** [comment]
Here's the previous impl: https://github.com/CronCats/contracts/blob/main/manager/src/tasks.rs#L359-L367

I dont think it needs to be "smart" enough to check amount of tasks agent skipped, as the idea is the agent skips any, they get a time they need to reset or else they get kicked. Keeps it super simple

**Comment by NinoLipartiia** [comment]
@TrevorJTClarke is it correct to say that we can keep the last slot when the agent called `proxy_call` (all the next slots are missing) instead of keeping `last_missed_slot`? I think it might be easier for this implementation.

Also I was wondering when bad agents should be ejected? Should anyone be able to call some method and unregister these agents (like `tick` in the previous implementation)?

**Comment by TrevorJTClarke** [comment]
> is it correct to say that we can keep the last slot when the agent called `proxy_call` (all the next slots are missing) instead of keeping `last_missed_slot`? I think it might be easier for this implementation.

@NinoLipartiia - Either way works for me! Prev impl didnt do that to reduce stored state, in this case we aren't state size bound ;) As long as we can keep track of if an agent hasn't done work required and kick after X period, then Im fine with a diff approach.

**Comment by TrevorJTClarke** [comment]
> Also I was wondering when bad agents should be ejected? Should anyone be able to call some method and unregister these agents (like `tick` in the previous implementation)?

Good question - so 2 things:
1. "Tick" method was actually a task (just like any other task) that the DAO scheduled for cleanup & agent management. I would like to keep this similar, as we can think of other future "business tasks" that croncat manager can utilize its own agents to do. This would be good to add tests for as well.
2. Bad agents should get reviewed/kicked inside the "tick" task. "Bad" agents are agents that have missed X slots or X blocks they needed to execute. There should be a configuration for X slots and X blocks configurable by the contract owner.
