### ISSUE TITLE
[Testing] to_hash and to_hash_vec

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/cw-croncat#15]
We can see here:
https://github.com/CronCats/cw-croncat/blob/c63bd6268ba6e8e238c5439c30b3b749246e8256/packages/cw-croncat-core/src/types.rs#L157-L175

That there are to methods that need to be covered by tests.

- [ ] `to_hash`
- [ ] `to_hash_vec`

These are fairly straightforward tests, and it's most useful so that in the future if these gets modified, we can catch errors before they become a problem.

I think it makes sense to add tests to the bottom of the `types.rs` file, which is located in `packages/cw-croncat-core/src/types.rs`

The test should create a `Task` struct with hardcoded values for the necessary fields (`owner_id`, `interval`, etc.) and ensure both functions return what's expected.

**Comment by Buckram123** [comment]
Closed by #29
