### ISSUE TITLE
[BUG] Task balance handler breaks

### ISSUE THREAD

**Issue by TrevorJTClarke** [CronCats/cw-croncat#151]
See: https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-croncat/src/manager.rs#L470

This needs logic to handle native tokens, cw20s, and when there are no tokens (empty vec).
Currently hardcoded 0 index causes proxycall to fail, which breaks rescheduling.

**Comment by mikedotexe** [comment]
Curious about this one. Does this breaking happen often?
