### ISSUE TITLE
Agent needs to fetch tasks with rules

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/cw-croncat#160]
Currently, the method `query_get_agent_tasks` only returns block and time-based tasks. See:

https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-croncat/src/agent.rs#L85-L107

I see that the primary struct `CwCroncat` is using these extra fields for rules:

https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-croncat/src/state.rs#L116-L121

This ticket is to add a new query function `query_get_agent_tasks_rules` that the agent will call to get all the tasks with rules. We don't need to use the balancer for this.

**Comment by Buckram123** [comment]
> Currently, the method `query_get_agent_tasks` only returns block and time-based tasks. See:
> 
> https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-croncat/src/agent.rs#L85-L107
> 
> I see that the primary struct `CwCroncat` is using these extra fields for rules:
> 
> https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-croncat/src/state.rs#L116-L121
> 
> This ticket is to add a new query function `query_get_agent_tasks_rules` that the agent will call to get all the tasks with rules. We don't need to use the balancer for this.

Hey, we have a method called `get_tasks_with_rules`! Or did I miss that we decided to bind tasks with rules to the agents?

**Comment by TrevorJTClarke** [comment]
@mikedotexe as @Buckram123 said, we have the method already: https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-croncat/src/tasks.rs#L44

Def could use optimizations in future, but this is all that is needed for the agent to query and use
