### ISSUE TITLE
If active agents is empty, the first pending agent should have Nominated status

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/cw-croncat#181]
For this ticket, we can use this Juno testnet address for the Manager contract:

`juno1cz5ru2px6cr4l27rxyk7md7976ezgeh8tu3mumhwp3ua2wspcfxszss3mr`

Clone the agent:
https://github.com/CronCats/croncat-rs

If you don't have two agents registered, make sure to create both with the commands:

    cargo run generate-mnemonic
    cargo run generate-mnemonic --new-name aloha

In the agent's codebase, change the value of `contract_address` to be the one above, in `config.uni-5.yaml`.

Then run:

    cargo run register-agent --chain-id uni-5

This will read the contract from the `config.uni-5.yaml` and attempt to register. It should succeed and look like this:

<img width="1259" alt="Screen Shot 2022-10-26 at 6 59 38 PM" src="https://user-images.githubusercontent.com/1042667/198173422-c09c8483-e7d5-44bf-93d5-8da64ab91444.png">

You can check the agents on the contract using the following `junod` command:

    junod q wasm contract-state smart juno1cz5ru2px6cr4l27rxyk7md7976ezgeh8tu3mumhwp3ua2wspcfxszss3mr '{"get_agent_ids":{}}' --node https://juno-testnet-rpc.polkachu.com:443 --chain-id uni-5 -o json | jq

(Make sure you have installed or install [`jq`](https://stedolan.github.io/jq/))

At this point, it should return something like this:

```json
{
  "data": {
    "active": [
      "juno1hntaw5cgvxz0gftpd9gec876n0l6az20clrred"
    ],
    "pending": []
  }
}
```

Next, let's register the second agent:

    cargo run register-agent --chain-id uni-5 --sender-name aloha

Now both will be there when you run the `juno` query command, one in the active, one in the pending. Now let's have the active agent unregister

    cargo run unregister-agent --chain-id uni-5

If you run the `junod` query again, you'll see there are no active agents, and there is one agent in the pending queue. This agent should have a status of "Nominated" because we want them to enter the active queue.

You can see, however, that the status is Pending. Something is wrong with that logic there. You can query to see the agent details including status with a command like this:

    junod q wasm contract-state smart juno1cz5ru2px6cr4l27rxyk7md7976ezgeh8tu3mumhwp3ua2wspcfxszss3mr '{"get_agent":{"account_id":"juno1hntaw5cgvxz0gftpd9gec876n0l6az20clrred"}}' --node https://juno-testnet-rpc.polkachu.com:443 --chain-id uni-5 -o json | jq

You'll see something like this:

```
{
  "data": {
    "status": "Pending",
    "payable_account_id": "juno1hntaw5cgvxz0gftpd9gec876n0l6az20clrred",
    "balance": {
      "native": [],
      "cw20": []
    },
    "total_tasks_executed": 0,
    "last_executed_slot": 505822,
    "register_start": "1666836892900035336"
  }
}
```

**Comment by Buckram123** [comment]
Hey @mikedotexe not sure if we want the first agent to be `Nominated` or instantly promoted @mikedotexe ? If we auto-promote first registered agent instantly to the active queue - to me it's intuitively to do the same (auto-promote first pending) if last active got unregistered/kicked. Thoughts?

**Comment by mikedotexe** [comment]
> not sure if we want the first agent to be `Nominated` or instantly promoted 

Let's keep it the way we've had it before, where each pending agent still needs to "Nominate" themselves. Let's not automatically have the first pending agent put into the active slot. It's possible that it's been a long time since the pending agent got into the queue, and maybe they're offline.

**Comment by Buckram123** [comment]
@mikedotexe makes sense, I'll fix it in my pr
