### ISSUE TITLE
Missing errors from replies during proxy calls

### ISSUE THREAD

**Issue by Buckram123** [CronCats/cw-croncat#184]
If one of the messages fails we may want to see error details, so let's echo it in events of the `reply` method!
Right now it's hard to find why one(or more) of the messages didn't went through

**Comment by mikedotexe** [comment]
Interesting, can we get some instructions on how to reproduce it?

**Comment by NinoLipartiia** [comment]
This happens if we try to execute DAO proposal with croncat task, but croncat isn't allowed to execute proposals of this DAO. In this case `proxy_call` succeeds, but proposal still has `Passed` status.
