### ISSUE TITLE
`funds_withdrawn_recurring` doesn't include cw20s

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/cw-croncat#190]
If you look at the `funds_withdrawn_recurring` here (which seems to be the only place where it's set):

https://github.com/CronCats/cw-croncat/blob/18c2f963757ed12df97007708ba04320777043aa/contracts/cw-croncat/src/manager.rs#L497-L505

It doesn't include cw20s. I think in the early days, this will be fine, but this ticket is hopefully not too difficult, and is meant to add a way to keep track of the cw20s that have been withdrawn.

Note that in the `Task` struct, we have the `funds_withdrawn_recurring` stored as a `Vec<Coin>` which implies native tokens:
https://github.com/CronCats/cw-croncat/blob/18c2f963757ed12df97007708ba04320777043aa/packages/cw-croncat-core/src/types.rs#L313

But I believe it should probably be a `GenericBalance` like a couple other fields, like:
https://github.com/CronCats/cw-croncat/blob/18c2f963757ed12df97007708ba04320777043aa/packages/cw-croncat-core/src/types.rs#L319

**Comment by deveusss** [comment]
@mikedotexe agree on it)

**Comment by mikedotexe** [comment]
Since we decided to remove that field in #176 going to close this, since we'll no longer use it
