### ISSUE TITLE
Adding useful reply data to `create_task`

### ISSUE THREAD

**Issue by whalelephant** [CronCats/cw-croncat#207]
Aim: Increase usability of `create_task` msg

(This might be useful for other messages)

At the moment, to use cw-croncat to `create_task` we rely on the reply attributes in the wasm event to get the `task_hash` to [update our state](https://github.com/nymlab/vectis-plugins/blob/8215707eee771f8dccad5ded3f688fb8bd5e8b6c/cronkitty/src/lib.rs#L53). 

Perhaps it can be return in the `data` field of the `Response` so it can be easily parsed.

**Comment by TrevorJTClarke** [comment]
great idea @whalelephant -- will do :)

**Comment by deveusss** [comment]
hey @whalelephant , we are giving task hash when calling create_task query
https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-croncat/src/tasks.rs#L413
