### ISSUE TITLE
[FIX] Move changes on master to splitted contracts

### ISSUE THREAD

**Issue by deveusss** [CronCats/cw-croncat#263]
Move list of PRs below into spliited contracts
[Block Slot Fix](https://github.com/CronCats/cw-croncat/pull/254) 
[Balancer Fix](https://github.com/CronCats/cw-croncat/pull/268)
[Task Prefix](https://github.com/CronCats/cw-croncat/pull/261)

**Comment by TrevorJTClarke** [comment]
Add prefix/d task hash's

**Comment by deveusss** [comment]
Task prefix moved!
Balancer fix moved!
