### ISSUE TITLE
Beta Factory: Migration Logic and Paused Contracts Removal Logic

### ISSUE THREAD

**Issue by TrevorJTClarke** [CronCats/cw-croncat#269]
Setup migration logic for using versions to instantiate and migrate. Needs test cov

**Comment by Buckram123** [comment]
Setup removal of non-library contracts, to check if contract is paused
Note: we only need to deserialize one field so the struct can be 
```rust
#[derive(Deserialize)]
struct CheckIfConfigIsPaused {
  pub paused: bool,
}
```
Unknown fields will get ignored, [by default](https://serde.rs/container-attrs.html#deny_unknown_fields)

**Comment by Buckram123** [comment]
> @Buckram123 can you explain more about this struct, why we are creating CheckIfConfigIsPaused?
Hey!
https://github.com/CronCats/cw-croncat/wiki/%F0%9F%8F%AD-Factory-Architecture#execute-msgs
This logic
```
Checks the contract is not VersionKind::Library, then checks if contract is paused, then is able to remove this version 
record from all storage maps.
```

**Comment by deveusss** [comment]
> > @Buckram123 can you explain more about this struct, why we are creating CheckIfConfigIsPaused?
> > Hey!
> > https://github.com/CronCats/cw-croncat/wiki/%F0%9F%8F%AD-Factory-Architecture#execute-msgs
> > This logic
> 
> ```
> Checks the contract is not VersionKind::Library, then checks if contract is paused, then is able to remove this version 
> record from all storage maps.
> ```

So this is execute message param?

**Comment by Buckram123** [comment]
> So this is execute message param?

No, it simply checks contract's `config.paused` and removes it from factory map
