### ISSUE TITLE
Inconsistent return type for `tasks_by_owner`

### ISSUE THREAD

**Issue by whalelephant** [CronCats/cw-croncat#345]
This is on branch beta/split-0.0.0, feel free to close if address on other branches. 

The response type from the [contract implementation - `Vec<TaskInfo>`](https://github.com/CronCats/cw-croncat/blob/19e8e148b77fa3a9a61cfaf7ceb7d998c921b8f6/contracts/croncat-tasks/src/contract.rs#L747) is different to one defined in the [queryMsg - `Vec<TaskResponse>`](https://github.com/CronCats/cw-croncat/blob/19e8e148b77fa3a9a61cfaf7ceb7d998c921b8f6/packages/croncat-sdk-tasks/src/msg.rs#L112).

Happy to fix but want to make sure we do want change it to `TaskInfo`, similar the `QueryMsg::Tasks`.

**Comment by TrevorJTClarke** [comment]
thats a great find @whalelephant -- feel free to PR or we'll nab it at the next round of merges

**Comment by TrevorJTClarke** [comment]
This is closed in `beta-0.1.2`
