### ISSUE TITLE
Support multiple actions

### ISSUE THREAD

**Issue by Buckram123** [CronCats/cw-croncat#54]
Currently if we try to create a task with multiple actions it will fail in `reply()` here: 
https://github.com/CronCats/cw-croncat/blob/a00b5780b9f4424577554d39a54fbed1065a546b/contracts/cw-croncat/src/contract.rs#L184-L185
Notice here `next_idx` stays the same, so after first reply second will fail this transaction
https://github.com/CronCats/cw-croncat/blob/a00b5780b9f4424577554d39a54fbed1065a546b/contracts/cw-croncat/src/manager.rs#L186-L193

Not sure yet what we want to do here, but few ideas:

1. Remove `QueueItem` only after it's the last response? (in short, we add a counter corresponding to the number of actions)
2. increment `next_idx` in a `proxy_call()`, so it's different `QueueItem`'s. There is actually currently unused field `prev_idx`

**Comment by deveusss** [comment]
@Buckram123 do you have an idea, how we could fix this?
