### ISSUE TITLE
CW-RULES: Balance Query Methods support

### ISSUE THREAD

**Issue by TrevorJTClarke** [CronCats/cw-croncat#61]
Requirements:
- [ ] Using branch: https://github.com/CronCats/cw-croncat/pull/60
- [ ] Add support for querying native & cw20 balances with the two methods: `GetBalance` & `GetCW20Balance`
- [ ] Create a new query msg that allows checking if balances are greater than passed in balance amount (either in native or CW20). Goal being: I can create a "rule" that checks if address has enough balance and returning TRUE.

**Comment by deveusss** [comment]
@NinoLipartiia closing this one right?

**Comment by NinoLipartiia** [comment]
@deveusss Yes, it is done
