### ISSUE TITLE
CW-RULES: DAO Proposal Passed

### ISSUE THREAD

**Issue by TrevorJTClarke** [CronCats/cw-croncat#62]
Requirements:
- [ ] Using branch: https://github.com/CronCats/cw-croncat/pull/60
- [ ] Add support for querying a dao proposal and checking if status matches "execute" (or whatever the DAODAO enum is)
- [ ] Should enable a "rule" to be created that evaluates to TRUE if status on proposal is ready for execution.

**Comment by deveusss** [comment]
@NinoLipartiia Closing?

**Comment by NinoLipartiia** [comment]
I think @Buckram123 has finished it, right?

**Comment by Buckram123** [comment]
Closed by #66
