### ISSUE TITLE
CW-RULES: Generic MSG deserialize/serialize + stacking

### ISSUE THREAD

**Issue by TrevorJTClarke** [CronCats/cw-croncat#64]
GOAL:
Allow multiple rules to stack for enabling very complex logical paths pre-execution. This is only possible IF the deserialization is possible on-chain.
The stacking of query messages and their internal variables is key here. If a rule does not need previous arguments, then it can simply be evaluated in a serial fashion. If a rule needs variables computed from previous query, then stacking with input enables a vast amount of other possibilities.

Example use case:
`If the prices of NFT is above XX price, and I am NOT the owner of NFT, place a bid/buy on the NFT.`

Which breaks down to:
1. `query price of NFT`
2. `use price to check if above XX in another helper method in cw-rules`
3. `query owner of NFT`
4. `EXEC buy msg`

Basic data structures:
```
// Request:
{
  contract_address: "",
  msg: ""
}
```

```
// pub type RuleResponse<T> = (bool, T);
(true, "some_parsable_format_here")
```

Critical Items to research:
- [ ] non-float deserialize for msg matching, using the second piece of tuple RuleResponse as the parsed data
- [ ] msg serialization with unknown msg structs

Requirements:
- [ ] Using branch: https://github.com/CronCats/cw-croncat/pull/60
- [ ] Add support for generic rules, looping through each rule and then stacking previous response if any
- [ ] "Stack" each next query (first one doesnt need, as we dont have data yet), where the previous second piece of tuple RuleResponse should get injected as a variable within the next rule msg
- [ ] Final outcome of this query function should return RuleResponse where the `T` is the output of the LAST rule output

**Comment by deveusss** [comment]
@Buckram123 Can we close this one?

**Comment by Buckram123** [comment]
> @Buckram123 Can we close this one?

I think we might need some improvements in stacking

**Comment by TrevorJTClarke** [comment]
@Buckram123 is this line right?
https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-rules/src/contract.rs#L250
I thought it was just for raw contract storage, but didnt return smart query response types.

So basically my guess is that, while it returns something, its not going to return data that can be reasoned about.

Goal of this issue is to figure out how to query then "parse" in a manner that we can return https://github.com/CronCats/cw-croncat/blob/main/packages/cw-rules-core/src/msg.rs#L43

Is that possible?

**Comment by TrevorJTClarke** [comment]
> We can't support every cosmwasm contract, so I thought of generic rules as a tool with which user can query any smart contract and get `true` or `false`.

Yeah - thats correct. Sorry not trying for confusion, just hoping to clarify (maybe its working?) so it works as intended.

There's 2 needed use cases, both of which **require** the queryable contract to implement `RuleResponse<T> = (bool, T)`.
The 2 cases:
1. Single query - based on the task rule, make a query to "msg" and return response `boolean` so proxy_call can decipher if it will execute task.
2. Cascading queries:
  A. Using cascading flow (call first query, check if response is `TRUE` before proceeding to next query)
  B. Each query utilizes the previous response `T` data, unless it is the first of series
  C. Response `T` becomes the `msg` payload of the next query, so chaining/cascading flows can be done.

For second style, you can think of a use case like:
> Does user have "CAT" NFT? Yes, pass in "CAT" NFT ID (using response `T`) into next query: Is user part of "CAT" DAO? Yes, pass in DAO contract address (using response `T`) into next query: User "juno" balance above 1000000ujuno? Yes, execute
Kinda weird use case, but you can see how the response plays a vital role in forwarding data to future queries to allow contract developers super flexibility in stacked logic.

**Comment by TrevorJTClarke** [comment]
IDEAL:
```
{
   msg: T,
   other: '',
   stuff: ''
}
```

Fallback plan:
```
{ ...T }
```

**Comment by TrevorJTClarke** [comment]
https://github.com/CronCats/cw-purrbox/blob/main/contracts/multi-query/src/contract.rs#L123-L170

**Comment by TrevorJTClarke** [comment]
closing this, as #176 covers it
