### ISSUE TITLE
[MVP] End-to-end QA — recurring Bank messages

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/cw-croncat#82]
This ticket involves writing a basic guide so that we can test recurring Bank messages.

So:

1. production build command
2. Add alice, bob, and charlie users if they don't exist
3. deploy command using `junod` or `wasmd`
4. instantiate
5. Add task from alice that pays bob and charlie .000001 JUNO every hour (or 5 minutes, whatever) (can use https://crontab.guru)
6. set up agent using https://github.com/CronCats/croncat-rs
7. watch agent call proxy_call
8. Confirm it repeats
9. Confirm the balance decreases on the task
10. Confirm bob and charlie get paid

**Comment by TrevorJTClarke** [comment]
Bonus points for doing an array of bankmsgs for 1 task :)
