### ISSUE TITLE
[MVP] End-to-end testnet QA — simplest Task with 1 rule

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/cw-croncat#83]
This ticket involves writing a basic guide so that we can test that the rules are working.

So:

1. production build command
2. Add alice if they don't exist
3. deploy command using `junod` or `wasmd`
4. instantiate
5. Add task from alice that has 1 rule, checking whether a given DAO DAO proposal's status is "passed" (or whatever that Enum value is. (See https://github.com/DA0-DA0/dao-contracts/blob/cef33570e41c52b04acd692cdd527c836185fd13/packages/voting/src/status.rs#L7-L21)
6. set up agent using https://github.com/CronCats/croncat-rs
7. watch agent call proxy_call, giving the task hash if it evaluates to true
8. Confirm the transaction is successful
9. Confirm the DAO DAO proposal is executed.

We can use this testnet DAO DAO DAO:
https://testnet.daodao.zone/dao/juno1p2fuar474uv2p6vfnr2eu4nv9rx4m0qd26xuygkesje0r6pzhrssvrnh2y

**Comment by deveusss** [comment]
hey @NinoLipartiia, any progress on this one?
